### ISSUE TITLE
Starting local network try to connect to seeds?

### ISSUE THREAD

**Issue by PaulBernier** [FactomProject/factomd#1019]
Starting a local network the following will keep being printed:
```
INFO[0122] Failed to dial to 123.45.6.7:9999             error="dial tcp :0->123.45.6.7:9999: connect: network is unreachable" network=LocalNet node=FNode0 package=p2p port=8110 subpack=controller
INFO[0123] Failed to dial to 76.54.32.1:9999             error="dial tcp :0->76.54.32.1:9999: connect: network is unreachable" network=LocalNet node=FNode0 package=p2p port=8110 subpack=controller
INFO[0123] Failed to dial to 234.56.78.9:9999            error="dial tcp :0->234.56.78.9:9999: connect: network is unreachable" network=LocalNet node=FNode0 package=p2p port=8110 subpack=controller
```
Those appear to be seeds from here: https://raw.githubusercontent.com/FactomProject/factomproject.github.io/master/seed/localseed.txt

- Why does a local network need seeds in the first place?
- Should we skip seeds when starting a local network?
@WhoSoup

**Comment by WhoSoup** [comment]
I believe those were from an Inc. local testnet. I agree they don't make sense as the default for everyone

**Comment by carryforward** [comment]
these were distinct IPs that were used to see if the list was being loaded.  1234567, 7654321, 23456789
