### ISSUE TITLE
Rework logging

### ISSUE THREAD

**Issue by PaulBernier** [FactomProject/factomd#1036]
After Wax release there are 3 logging systems:

- logrus
- https://github.com/FactomProject/factomd/blob/FD-1225_wax_rollup/log/log.go
- https://github.com/FactomProject/factomd/blob/FD-1225_wax_rollup/modules/logging/newLogger.go

This needs to be simplified/unified.

**Comment by WhoSoup** [comment]
I looked at logger benchmarks and there are some interesting alternatives, such as [ZeroLog](https://github.com/rs/zerolog) and ][ZAP](https://github.com/uber-go/zap). 

Logrus usually looks pretty bad in benchmarks such as http://hackemist.com/logbench/, however there is one interesting benchmark stat: https://github.com/imkira/go-loggers-bench

If you look at "TextNegative", aka the performance of logging for items that are **disabled**, logrus comes out in top. This is the situation for most of factomd's logging where loglvl=warn and it suppresses all info/debug messages. That's not the case for JSON logging, however, only text.

If we switch to JSON logging, I think standardizing everything to zerolog/zap might make sense.
