### ISSUE TITLE
Remove bogus "MinuteNumber.GetSigHash() returned a nil for IHash" error.

### ISSUE THREAD

**Issue by PaulSnow** [FactomProject/factomd#1053]
GitSigHash() isn't defined for MinuteNumber, so it always returns a nil.  It shouldn't be checked.
`
MinuteNumber.GetSigHash() returned a nil for IHash. Called from goroutine 7220-/common/entryCreditBlock/minutenumber.go:74
`

**Comment by PaulSnow** [comment]
Already fixed in develop

**Comment by PaulBernier** [comment]
To be exact it has been fixed in Wax branch (https://github.com/FactomProject/factomd/pull/1021) but not develop (until we merge Wax into develop that is)
