### ISSUE TITLE
Fix 2nd pass % shown in Control Panel

### ISSUE THREAD

**Issue by PaulBernier** [FactomProject/factomd#1061]
![image](https://user-images.githubusercontent.com/5141652/94226088-8ad06f80-feab-11ea-87af-a16fc50758b4.png)

**Comment by sigrlami** [comment]
Is that still an issue for latest release 6.10 release ?

**Comment by WhoSoup** [comment]
> Is that still an issue for latest release 6.10 release ?

No, it was a 6.9 only thing
