### ISSUE TITLE
[6.10] Changelog

### ISSUE THREAD

**Issue by WhoSoup** [FactomProject/factomd#1106]
Since 6.10 is based off of 6.8 and not 6.9, I figured it would make more sense to write the changelog as if 6.9 didn't happen.

# Changelog v6.10.0-rc1

## Features
* ChainHeadFix reworked to be multithreaded and run faster to improve startup times
* P2P2 rework integrated
* Entry sync ("2nd pass") rewritten to limit the number of concurrent requests made

## API Changes
* Raw data is now optional for the methods: admin-block, factoid-block, entrycredit-block, dblock-by-height, ecblock-by-height, fblock-by-height,ablock-by-height. To retrieve without raw data, add a parameter "noraw" of "true". Factom client support is in the current developer build.
* Panics in API calls are now handled gracefully instead of shutting down the node

## Bugfixes
* Phantom pending coinbase no longer shows up
* Several unit tests fixed
* Don't display a "nil hash" error when someone buys EC

## Developer Changes
* The repo now uses go.mod to manage dependencies instead of glide
* Golang compiler version check is removed
* Automated circle test revamped to stop unnecessary checks on side branches and improve the flow (such as including go fmt and go vet checks)

**Comment by PaulBernier** [comment]
Thanks!

**Comment by sigrlami** [comment]
Thank you. We maintain multiple Factom clients and track any Api changes, changelog good place for that.

**Comment by PaulBernier** [comment]
I have used your change log for the v6.12.0 release: https://github.com/FactomProject/factomd/releases/tag/v6.12.0
