### ISSUE TITLE
CheckDecodeWithTwoVersionBytes

### ISSUE THREAD

**Issue by peterwillcn** [FactomProject/factomd#16]
#go get github.com/FactomProject/factomd
```
# github.com/FactomProject/factomd/common/primitives
src/github.com/FactomProject/factomd/common/primitives/conversions.go:53: undefined: "github.com/FactomProject/btcutil/base58".CheckDecodeWithTwoVersionBytes
src/github.com/FactomProject/factomd/common/primitives/conversions.go:75: undefined: "github.com/FactomProject/btcutil/base58".CheckDecodeWithTwoVersionBytes
```

**Comment by n1rvana** [comment]
In the factomd project, run all.sh m2
This is the m2 (development) version of factomd.  For the current production one, checkout factomproject/FactomCode
You may get the same error when running all.sh, in that case, 
Git clone our btcutil package, found here: https://github.com/FactomProject/btcutil/

**Comment by n1rvana** [comment]
No updates, assuming issue resolved.
