### ISSUE TITLE
prometheus dependency: compilation errors

### ISSUE THREAD

**Issue by lucvanbraekel** [FactomProject/factomd#207]
Compilation of factomd v0.4.0.3 fails with errors:

```state/entrySyncing.go:57: ESAsking.Set undefined (type prometheus.Counter has no field or method Set)
state/entrySyncing.go:58: ESAsking.Set undefined (type prometheus.Counter has no field or method Set)
state/entrySyncing.go:59: ESFound.Set undefined (type prometheus.Counter has no field or method Set)
state/entrySyncing.go:60: ESAvgRequests.Set undefined (type prometheus.Counter has no field or method Set)
state/entrySyncing.go:148: ESMissingQueue.Set undefined (type prometheus.Counter has no field or method Set)
state/entrySyncing.go:149: ESDBHTComplete.Set undefined (type prometheus.Counter has no field or method Set)
state/entrySyncing.go:150: ESFirstMissing.Set undefined (type prometheus.Counter has no field or method Set)
state/entrySyncing.go:151: ESHighestMissing.Set undefined (type prometheus.Counter has no field or method Set)
```

Checked with go 1.6 and 1.8.

Google shows these errors in other projects depending on prometheus. I suppose the factomd code is relying on an older version of prometheus?

**Comment by carryforward** [comment]
were you using "go get" ?  That isn't really the install procedure anymore.  we pin our dependent repositories using glide.

here are the latest install instructions:
https://github.com/FactomProject/FactomDocs/blob/master/installFromSourceDirections.md#install-factom

**Comment by lucvanbraekel** [comment]
Yes, I was using "go get".  Using glide as described in the link solved it. Thank you!
