### ISSUE TITLE
factoid balance is negative number in rpc respoce

### ISSUE THREAD

**Issue by 34ro** [FactomProject/factomd#224]
Hi
I found that balance of some factoid addresses are negative in rpc responce.
So I can't get correct balance.

for example
```
curl -X POST --data-binary '{"jsonrpc": "2.0", "id": 0, "method":
"factoid-balance", "params":{"address":"FA2gHchEjYhUwHrzdRUYYs2Z2tbAxHzD5JdFGGoaJT2f2n6xAE5t"}}' \
-H 'content-type:text/plain;' http://localhost:8088/v2
{"jsonrpc":"2.0","id":0,"result":{"balance":-47632489}}
```

**Comment by carryforward** [comment]
oh, wow, this is bad.  What were you doing when you saw this?  How long was the factomd you were using running?

**Comment by carryforward** [comment]
ok, we might have found the issue.  Let me know if it still occurs in v0.4.1.1, which was released today.

**Comment by 34ro** [comment]
factomd version is v0.4.0.1.
I'll up grade and try factoid-balance

**Comment by PaulSnow** [comment]
Current version is v0.4.1.2
