### ISSUE TITLE
factomd issue

### ISSUE THREAD

**Issue by lucarot92** [FactomProject/factomd#243]
Hi,
I updated the new binaries and the wallet but I have an issue, when I run factomd and I reach the 86000th block this is what happens:and it keeps doing this every 5/10 minutes.
can someone help?
I also tried to delete everything and restarting everything importing my wallet but nothing changed

FNode0 Loading Block   86000 / 86866. Blocks per second   146.42
Reading from '/Users/xxx/.factom/m2/factomd.conf'
Cannot open custom config file,
Starting with default settings.
open /Users/xxx/.factom/m2/factomd.conf: no such file or directory

**Comment by carryforward** [comment]
this is normal.  if you want to get rid of the message, you can save the factomd.conf file to the ~/.factom/m2/ directory.
https://raw.githubusercontent.com/FactomProject/factomd/master/factomd.conf
