### ISSUE TITLE
ERROR: Factom Wallet on Mac - Factomd 

### ISSUE THREAD

**Issue by ansonla3** [FactomProject/factomd#25]
I am using MacOS and tried to install wallet follow the guide in yours website.

When I first run the Factomd , it shown an error

/Applications/FactomApps/factomd ; exit;
2016/09/15 21:34:06 read factom config file:  /Users/xxxxx/.factom/factomd.conf
2016/09/15 21:34:06 ERROR Reading config file!
Server starting with default settings...

What is factomd.conf ? I did't see it

**Comment by carryforward** [comment]
That is an optional config file.  You only need it if you are going to do advanced configurations.  If you are not using multiple computers, etc, you can ignore that message.  It will use the defaults if it cannot find the config file.

for reference, the file is located here for the software you are running: https://raw.githubusercontent.com/FactomProject/FactomCode/master/factomd/factomd.conf
