### ISSUE TITLE
Experimantal Mac support for m1 factom

### ISSUE THREAD

**Issue by carryforward** [FactomProject/factomd#27]
Here are some mac binaries for the milestone 1 factom programs.

http://dropjar.com/#1a9clmdj

Sha256 sums:

579811e2feb0e3fa965bb239fea97157385c93adebeb175d78d355a542015a2a  mac_17_experiment.zip

ddd1219ea4abeb2b7822acdf68f90c31bac44eaa29e844f471defec2801a8c38  factom-cli
d722a55af520f30ee97a9ffeadd83a74e69d4bc1486bb9f9a79a2fe3196172da  factomd
b61670cb23cd1617dd81400e39cc6820fb784379c3de72e5b4a618441a8545b6  fctwallet
5b6549c03635eae27085a4ea19455c407f271031dde56989856e5481853035fd  walletapp

**Comment by zbsb** [comment]
@carryforward 
Thank you, however would you mind verifying the link you posted.  I arrive at dropjar (main page I believe).  Interesting faces, but no files.  Am I mistaken?  :-?

**Comment by carryforward** [comment]
[mac_17_experiment.zip](https://github.com/FactomProject/factomd/files/538073/mac_17_experiment.zip)
ok, I updated the link.  also the file is attached here.

**Comment by zbsb** [comment]
thanks

**Comment by carryforward** [comment]
please try the new mac installer.
https://github.com/FactomProject/distribution
