### ISSUE TITLE
go run time version check issue

### ISSUE THREAD

**Issue by compasses** [FactomProject/factomd#285]
want to know why need check version like this ：
if strings.Contains(runtime.Version(), "1.5") {
		goodenough = true
	}
....
could just check whether the go version later than 1.5?
cause if use go 1.8 , the factomd can not start.

**Comment by carryforward** [comment]
are you looking at an older version of the sourcecode?  1.8 has been tested and supported for a while.

https://github.com/FactomProject/factomd/blob/master/engine/factomd.go#L71

Despite golang's promise not to introduce reverse compatible breaking changes, we have observed that not to be the case.  when we upgraded from 1.6 to 1.7, factomd was panicing with some newly introduced rules.

The code you are pointing at is basically the versions we have tested it on.  if you are building from source on a new version, feel free to disable that code.  It will most likely work, but the future is uncertain.

**Comment by compasses** [comment]
thanks
