### ISSUE TITLE
Big difference between M2 and M1, missing anchor part

### ISSUE THREAD

**Issue by compasses** [FactomProject/factomd#296]
Hi, for M2 code, no anchor part found, so how could i enable it?
anyway is there any explanation about M2 in compare with M1?
big thanks.

**Comment by PaulSnow** [comment]
We moved the anchoring out of the main branch into a separate Anchor maker.  I don't think we have released that code yet.

**Comment by PaulSnow** [comment]
M2 supports multiple leaders, and syncs over the network in real time.  
M1 is single leader/client only, and syncs only at the block level (every 10 minutes, like Bitcoin).
