### ISSUE TITLE
CheckDecodeWithTwoVersionBytes undefined

### ISSUE THREAD

**Issue by 4gn3s** [FactomProject/factomd#3]
Hello,
when trying to build factomd, I get the following errors:
```sh
# github.com/FactomProject/factomd/common/primitives
src/github.com/FactomProject/factomd/common/primitives/conversions.go:53: undefined: "github.com/FactomProject/btcutil/base58".CheckDecodeWithTwoVersionBytes
src/github.com/FactomProject/factomd/common/primitives/conversions.go:75: undefined: "github.com/FactomProject/btcutil/base58".CheckDecodeWithTwoVersionBytes
```

I fixed this by using CheckDecode in those lines instead. It is a correct solution?

**Comment by PaulSnow** [comment]
This is milestone 2 code, and is very experimental and mostly broken.

The current release is in the FactomCode repository.

**Comment by 4gn3s** [comment]
Thank you for the quick response. I'll try FactomCode instead.
