### ISSUE TITLE
Ubuntu run out of inodes on due to factomd

### ISSUE THREAD

**Issue by igorbarinov** [FactomProject/factomd#31]
Hi guys,
I host factomd in production for Blocknotary Classic iOS app https://itunes.apple.com/us/app/blocknotary-bitcoin-blockchain/id998052799?mt=8

Recently, notarization with Factom stopped to work with no space left on device error
```
root@factom:~# factomd
2016/11/07 17:21:07 read factom config file:  /root/.factom/factomd.conf
Go compiler version: go1.6.2
boltDBpath: /root/.factom/
panic: open /root/.factom/ldb/315445.ldb: no space left on device
```

The server had plenty of disk space
```
root@factom:~/# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        30G   17G   12G  58% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
udev            487M  4.0K  487M   1% /dev
tmpfs           100M  324K  100M   1% /run
none            5.0M     0  5.0M   0% /run/lock
none            498M     0  498M   0% /run/shm
none            100M     0  100M   0% /run/user
```

But ran out of inodes

```
Filesystem      Inodes   IUsed  IFree IUse% Mounted on
/dev/vda1      1966080 1966080      0  100% /
none            127234       2 127232    1% /sys/fs/cgroup
udev            124520     402 124118    1% /dev
tmpfs           127234     307 126927    1% /run
none            127234       1 127233    1% /run/lock
none            127234       1 127233    1% /run/shm
none            127234       2 127232    1% /run/user
````
I used script to find where the server ran out of inodes

```
for i in /root/.factom/*; do echo $i; find $i |wc -l; done
```

I found that `data` folder ate all inodes

```
./000000000000000000000000000000000000000000000000000000000000000c
3302
./000000000000000000000000000000000000000000000000000000000000000d
3302
./000012.ldb
1
./000013.ldb
1
./000014.ldb
1
./000015.ldb
1
./000018.log
1
./btcd.log
1
./CURRENT
1
./data
1618889
```

Questions:
- how do you deal with this in your environment?
- what can I do now to fix my server?

**Comment by carryforward** [comment]
Yes, this is indeed a problem.

You might run into an issue starting factomd after you get this running.  I would suggest the latest release:  https://github.com/FactomProject/distribution

The problem you are seeing now, though is unrelated to that.  feel free to delete the .factom/data/ folder.  it is mostly just for debugging.   

To solve this issue, set the
`logLevel	= info` in the factomd.conf file.  If it is set to debug, it creates these files.


Without a config file, the loglevel defaults to info.

**Comment by igorbarinov** [comment]
@carryforward thank you, I removed the `.factom/data/` folder, updated to 0.3.8.0 and set `logLevel  = info`

now waiting for confirmation after submitting a transaction, for like 30 mins. How do I check if my blockchain is synced?

**Comment by carryforward** [comment]
It does take a while and the feedback is a little lacking.

The best way is to run `factom-cli get height`.  That should match explorer height 62259 right now.
http://explorer.factom.org/

**Comment by igorbarinov** [comment]
Good, now it's synced. Thank you! 

Here is a photo of happy notarized file:

![img_5920](https://cloud.githubusercontent.com/assets/424628/20084487/8cf5394a-a517-11e6-9f5d-c6834b228b3a.PNG)
