### ISSUE TITLE
panic on anchor ETH

### ISSUE THREAD

**Issue by compasses** [FactomProject/factomd#312]
{"AnchorRecordVer":1,"DBHeight":2164,"KeyMR":"8d957d53ee7ee5ef68554393ce5cc2c71b6eac34131bb88214d2ee7be211cd5f","RecordHeight":0,"Ethereum":{"Address":"0x100c8b406978a413c4305b3aa6074f734fee6c9c","TXID":"0x0bc369950e0d033ab9ef8251821b706ecd1e8d2fe9bc0b58761de51cb8ad5c7e","BlockHeight":1422065,"BlockHash":"0xddb8ffd35ceeff5149e10d56bbe0ae98be7b2d5c89cbd61c7ff50de40b51179d","Offset":1}}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x14847ec]

goroutine 70 [running]:
github.com/FactomProject/factomd/database/databaseOverlay.AnchorRecordToDirBlockInfo(0xc42172d100, 0x2, 0x2, 0x19a)
	/Users/jet/gocode/src/github.com/FactomProject/factomd/database/databaseOverlay/anchorInfo.go:156 +0xac
github.com/FactomProject/factomd/database/databaseOverlay.(*Overlay).SaveAnchorInfoFromEntryMultiBatch(0xc42044b1a0, 0x1c4f200, 0xc421746d20, 0x40, 0x1)
	/Users/jet/gocode/src/github.com/FactomProject/factomd/database/databaseOverlay/anchorInfo.go:90 +0x3e6
github.com/FactomProject/factomd/database/databaseOverlay.(*Overlay).InsertEntryMultiBatch(0xc42044b1a0, 0x1c4f200, 0xc421746d20, 0xc4212739e8, 0x569f5e2fc678a501)
	/Users/jet/gocode/src/github.com/FactomProject/factomd/database/databaseOverlay/entry.go:54 +0x6ae
github.com/FactomProject/factomd/state.(*DBStateList).SaveDBStateToDB(0xc42044b140, 0xc42014a690, 0xc42014a600)
	/Users/jet/gocode/src/github.com/FactomProject/factomd/state/dbStateManager.go:1276 +0x13db
github.com/FactomProject/factomd/state.(*DBStateList).UpdateState(0xc42044b140, 0xc4000008dc)
	/Users/jet/gocode/src/github.com/FactomProject/factomd/state/dbStateManager.go:1385 +0x10f
github.com/FactomProject/factomd/state.(*State).UpdateState(0xc420412000, 0x0)
	/Users/jet/gocode/src/github.com/FactomProject/factomd/state/state.go:1654 +0xd0
github.com/FactomProject/factomd/state.(*State).ValidatorLoop(0xc420412000)

**Comment by itgb** [comment]
Hello, I am also dedicated to develop apps based on factom. If you like, we can share something with each other. It's lonely that there are no others to communicate about factom.

**Comment by carryforward** [comment]
@itgb The Factom community is anything but lonely.  Get live community support here:

https://discord.gg/VgNqE8W
