### ISSUE TITLE
package github.com/FactomProject/btcutil/certs: cannot find package

### ISSUE THREAD

**Issue by peterwillcn** [FactomProject/factomd#32]
go get github.com/FactomProject/factomd
package github.com/FactomProject/btcutil/certs: cannot find package "github.com/FactomProject/btcutil/certs" in any of:
	/opt/golang/current/src/github.com/FactomProject/btcutil/certs (from $GOROOT)
	/xxx/work/src/github.com/FactomProject/btcutil/certs (from $GOPATH)

**Comment by carryforward** [comment]
https://factom.com/blog/factom-launches-federated-testnet

you need to run the script all.sh to get all the right dependencies.

**Comment by peterwillcn** [comment]
./all.sh m2
work. Thanks.
