### ISSUE TITLE
Internal error: secret key portion must be 32 bytes

### ISSUE THREAD

**Issue by JulienWu** [FactomProject/factomd#33]
root@ubuntu:~# $GOPATH/bin/factom-cli newfctaddress
Internal error: secret key portion must be 32 bytes

**Comment by carryforward** [comment]
are you trying to experiment with milestone 2 code?  are you using an older version of factom_wallet.db ?

are you running the m2-rc1 version of factom-walletd?  are these the directions you followed?  https://factom.com/blog/factom-launches-federated-testnet

**Comment by carryforward** [comment]
I have not seen this error before.  would you please email your ~/.factom/m2/factom_wallet.db file to brian@factom.org or post it here?  When was the first time you installed factom?

**Comment by carryforward** [comment]
ok, we are seeing this internally and are able to reproduce it.

**Comment by carryforward** [comment]
Nice find.  This turned out to be a bug in the library we used.  
https://github.com/tyler-smith/go-bip32/issues/3
