### ISSUE TITLE
Losing connections

### ISSUE THREAD

**Issue by haggins** [FactomProject/factomd#36]
I'm using factomd on the m2-rc1 branch on Mint 18:
```
./all.sh m2-rc1
factomd
```

It starts with 7 connections and syncs a few blocks. After a couple of minutes it starts losing one connection after another until none is left (and no connection reappears) and I have to CTRL-C and restart.

What information can I provide to help pinning down the problem? There are no logs in `~/.factom/m2/test-database/Log`.
`~/.factom/m2/test-database/LogFNode0.log` is empty.

```
~ $ go version
go version go1.7.3 linux/amd64
```

Edit: syncing stopped at block 5000, then at 7200. Currently going forward...and finally finished.

**Comment by carryforward** [comment]
We did find a bug that caused those disconnections.  try rebuilding factomd with improved code.  from the ~/go/src/github.com/FactomProject/factomd directory run:
./all.sh cd5fe8dc4e585a3d4d6843fc490590915208424b m2-rc1

It was compensated for in this commit: https://github.com/FactomProject/factomd/commit/7e9a136f257f97d72176c8d59e07b29448a73070

An issue we are seeing now is that it pulls down too much bandwidth.  It might saturate your download capacity while syncing.

**Comment by haggins** [comment]
Thanks, disconnections gone! The bandwidth usage wasn't a problem because it only spiked every ~7sec to max 70% of the available bandwidth. Seems like 200 blocks are downloaded at a time and then processed, right?
Are these Factoid or Directory or Entry Blocks?
