### ISSUE TITLE
High CPU when STDIN not available

### ISSUE THREAD

**Issue by logicethos** [FactomProject/factomd#378]
I ran factomd in a docker container. The cpu usage went to 100%, and the log files filled up with:

"Error reading from std, sleeping for 5s: EOF"

This can be fixed in docker by using the -i parameter to keep STDIN open even if not attached.  I will write you some better docker instructions soon.

I would suggest disabling reading STDIN if it's not available.

**Comment by carryforward** [comment]
The problem is that there is a built in network simulator when you start factomd.  It uses stdin to control it.  When there is no stdin, it gets confused.  

To disable it, and get rid of the error and CPU, start factomd with this flag: -sim_stdin=false

**Comment by logicethos** [comment]
OK, thanks.
