### ISSUE TITLE
Preferred build platform?

### ISSUE THREAD

**Issue by gldneagl** [FactomProject/factomd#423]
What is the preferred build platform?

I just tried building on Ubunto 16.04 with nothing but issues. I only tried using this host because I already had it built awaiting other work.

Would this build properly on CentOS without issues with the location of GO, and beyond such as the errors I have pasted below?

It is actually MY preferred platform having been in RedHat for twenty years now.

root@hostname:~# go get github.com/FactomProject/factomd
# runtime
/usr/local/go/src/runtime/lfstack_amd64.go:16: lfstackPack redeclared in this block
        previous declaration at /usr/local/go/src/runtime/lfstack_64bit.go:37
/usr/local/go/src/runtime/lfstack_amd64.go:20: lfstackUnpack redeclared in thisblock
        previous declaration at /usr/local/go/src/runtime/lfstack_64bit.go:41
/usr/local/go/src/runtime/os_linux.go:27: _FUTEX_WAIT redeclared in this block
        previous declaration at /usr/local/go/src/runtime/os1_linux.go:22
/usr/local/go/src/runtime/os_linux.go:28: _FUTEX_WAKE redeclared in this block
        previous declaration at /usr/local/go/src/runtime/os1_linux.go:23
/usr/local/go/src/runtime/os_linux.go:36: futexsleep redeclared in this block
        previous declaration at /usr/local/go/src/runtime/os1_linux.go:31
/usr/local/go/src/runtime/os_linux.go:67: futexwakeup redeclared in this block
        previous declaration at /usr/local/go/src/runtime/os1_linux.go:62
/usr/local/go/src/runtime/os_linux.go:83: getproccount redeclared in this block
        previous declaration at /usr/local/go/src/runtime/os1_linux.go:78
/usr/local/go/src/runtime/os_linux.go:109: _CLONE_VM redeclared in this block
        previous declaration at /usr/local/go/src/runtime/os1_linux.go:104
/usr/local/go/src/runtime/os_linux.go:110: _CLONE_FS redeclared in this block
        previous declaration at /usr/local/go/src/runtime/os1_linux.go:105
/usr/local/go/src/runtime/os_linux.go:111: _CLONE_FILES redeclared in this block
        previous declaration at /usr/local/go/src/runtime/os1_linux.go:106
/usr/local/go/src/runtime/os_linux.go:111: too many errors
root@hostname:~#

**Comment by carryforward** [comment]
hmm, I have never seen an error like that.  the golang version that you get when running `apt get install golang` is very much out of date, and is untested.  

you can see which version of go you are running with

`go version`

Most of our testing is on 1.9 and we have transitioned to 1.10 recently.

https://github.com/FactomProject/FactomDocs/blob/master/installFromSourceDirections.md

**Comment by stackdump** [comment]
Late to the party - but maybe we want to declare that the base docker image is our perfered build
generally we don't have any dependencies beyond Go (and glide) 

we will attempt to keep the entire build toolchain installable via go & gomod
