### ISSUE TITLE
Whether facomd has implement the function that writting the anchor  into Bitcoin or Ethereum?

### ISSUE THREAD

**Issue by itgb** [FactomProject/factomd#424]
Just as the title says: Whether facomd has implement the function that writting the anchor  into Bitcoin or Ethereum?

I found the function has been implemented in factomCode, but not in factomd.  Is there anyone can know the details? Thanks a lot.

**Comment by carryforward** [comment]
Anchors in the blockchain can be found here: https://blockchain.info/address/1K2SXgApmo9uZoyahvsbSanpVWbzZWVVMF
