### ISSUE TITLE
Control Panel eats resources if left open. (updateAllPeers)

### ISSUE THREAD

**Issue by logicethos** [FactomProject/factomd#427]
If I leave the Control Panel open for a long time (overnight) I notice it becomes less responsive.  If left long enough, it will take 100% CPU.

updateHTML() & updateAllPeers() seems to be the culprit.  They can be slow to execute, and are being called too frequently.  Possibly before the previous call has finished.

I'm using the latest version of Chrome.
![image](https://user-images.githubusercontent.com/424601/36794202-9539661e-1c97-11e8-804b-86b8416c2d3e.png)

**Comment by carryforward** [comment]
yah, this is a longstanding issue.  The workaround at this point is to close and open the webpage.

**Comment by logicethos** [comment]
Would be nice in the future, if there was a websocket where you could request real-time data, instead of polling.  I realise that's low-priority right now.

Thanks for the acknowledgement.

**Comment by stackdump** [comment]
+1 on websocket
We've slated to rebuild the entire control panel during an upcoming refactor

I like how the PegNet control pannel makes use of Server-Send events
https://github.com/pegnet/pegnet/blob/master/controlPanel/controlPanel.gov

We'll also be adding a pub/sub type functionality to keep track of the system state.
