### ISSUE TITLE
Having an issue syncing factomd -  DROPPING MESSAGES and gob: unknown type id or corrupted data

### ISSUE THREAD

**Issue by DaveWK** [FactomProject/factomd#454]
I am trying to sync factomd v0.4.22 however see this repeatedly in the logs:
"component":"networking","level":"warning","msg":"nonBlockingChanSend() - DROPPING MESSAGES. Channel is over 90 percent full! \n channel len: \n 4751 \n 90 percent: \n 4750

then a lot of:
component":"networking","func":"HandleNetErrors","level":"warning","msg":"Going offline due to -- gob: unknown type id or corrupted data","package":"p2p","peer_type":"regular"

**Comment by carryforward** [comment]
the gob errors may be related to this:
https://github.com/FactomProject/factomd/pull/453

before this patch, when a connection was dropped and reconnected, the gob buffer was getting confused and would try to deserialize partial data.  We think this latest patch will solve this longstanding gob issue.
