### ISSUE TITLE
go install 

### ISSUE THREAD

**Issue by Futjrnn** [FactomProject/factomd#456]
expected experience: 
go install
installs

actual experience:

../../hashicorp/go-plugin/client.go:5:2: cannot find package "context" in any of:
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/home/futjrn/go/src/context (from $GOPATH)
../../../golang.org/x/crypto/ripemd160/ripemd160block.go:12:2: cannot find package "math/bits" in any of:
	/usr/lib/go-1.6/src/math/bits (from $GOROOT)
	/home/futjrn/go/src/math/bits (from $GOPATH)

I noticed math/bits and context were no got when I go get GitHub.com/factomproject/factomd

what do?

**Comment by carryforward** [comment]
go install is fairly limited in dependency finding and matching.  to pin dependencies, we use glide.yaml and glide.lock to keep upstream code changes from breaking our code.  First you should install glide, then run `glide install` to get the dependencies.  then go install will work.

https://github.com/FactomProject/FactomDocs/blob/master/installFromSourceDirections.md#install-factom

We have found some unexpected problems, where cached dependencies get goofed up a bit when using glide.  `glide cc` clears the cache and downloads the freshest dependencies.  This may or may not have been fixed.

Glide is becoming a less maintained project compared to go dep.  dep may be the future of package management for golang, but right now glide is how our dependencies are managed.  dep may read the glide.yaml and glide.lock files also.

**Comment by stackdump** [comment]
We'll be adopting gomod in the near future - this will hopefully lead to a better experience
