### ISSUE TITLE
go install context / mathbits not found

### ISSUE THREAD

**Issue by Futjrnn** [FactomProject/factomd#472]
futjrn@h3rcn0d3:~/go/src/github.com/FactomProject/factomd$ go install -ldflags "-X github.com/FactomProject/factomd/engine.Build=git rev-parse HEAD -X github.com/FactomProject/factomd/engine.FactomdVersion=cat VERSION" -v
../../hashicorp/go-plugin/client.go:5:2: cannot find package "context" in any of:
    /usr/lib/go-1.6/src/context (from $GOROOT)
    /home/futjrn/go/src/context (from $GOPATH)
../../../golang.org/x/crypto/ripemd160/ripemd160block.go:12:2: cannot find package "math/bits" in any of:
    /usr/lib/go-1.6/src/math/bits (from $GOROOT)
    /home/futjrn/go/src/math/bits (from $GOPATH)

getting this after a successful glide install, and then trying to go install. 

what do?

**Comment by carryforward** [comment]
ah, I understand.  older versions of golang didn't support the vendor directory that contains the dependencies that glide uses.

it looks like you are using an older version of golang (1.6)  The latest version is 1.10.  package managers don't keep up with the latest compiler versions.  you can doublecheck with `go version`.

Try it with the latest go version. https://github.com/FactomProject/FactomDocs/blob/master/installFromSourceDirections.md#install-the-go-language-and-dependencies-then-setup-gopath

**Comment by Futjrnn** [comment]
seems to still not register factomd as a command after purging go and reinstalling from go1.10.2 and redoing all glide installs

**Comment by carryforward** [comment]
continued here:
https://github.com/FactomProject/factomd/issues/476
