### ISSUE TITLE
factomd command not found

### ISSUE THREAD

**Issue by Futjrnn** [FactomProject/factomd#476]
I've tried and tried and cried
I've started with a fresh ubuntu env 
and have followed the instructions to a T
still getting factomd command not found. 

does this even work?

**Comment by Emyrk** [comment]
You most likely do not have your $PATH set you have golang and have successfully run "go install"

Can you do the following?
```
echo "GOPATH=`echo $GOPATH`"
echo "PATH=`echo $PATH`"
```

Finally, if your gopath is set, but path is not set to look at $GOPATH/bin, you can try this to run factomd:

```
$GOPATH/bin/factomd
``

**Comment by lrgeoemtry** [comment]
now its saying my GOPATH must not be set as GOROOT.

**Comment by lrgeoemtry** [comment]
cannot redownload glide

**Comment by Futjrnn** [comment]
echo "GOPATH=`echo $GOPATH`" 
GOPATH=/home/futjrn/go

echo "PATH=`echo $PATH`"
/src/github.com/FactomProject/factom-cli
glide install
go install -ldflags "-X main.FactomcliVersion=cat VERSION" -v
cd $GOPATH/src/github.com/FactomProject/factom-walletd
glide install
go install -ldflags "-X github.com/FactomProject/factom-walletd/vendor/github.com/FactomProject/factom/wallet.WalletVersion=cat ./vendor/github.com/FactomProject/factom/wallet/VERSION" -v
cd $GOPATH/src/github.com/FactomProject/enterprise-wallet
glide install
go install -v
cd $GOPATH/src/github.com/FactomProject/factomd
PATH=/home/futjrn/bin:/home/futjrn/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/futjrn/go/bin:/home/futjrn/go/bin

^don't ask me why, i exported PATH=$PATH:$GOPATH/bin 

still, though no factomd command

**Comment by Futjrnn** [comment]
there was one point long ago i got factomd working, now i want to bash my head in

**Comment by Emyrk** [comment]
@Futjrnn You have your paths set correctly. I don't have much information to go off of. Are you in our community discord? It's better for quick technical advice/questions.

If not, can you post the steps you are following? They should look like this:
```
cd $GOPATH/src/github.com/FactomProject/factomd
git checkout master && git pull
glide install
go install

factomd
```

**Comment by Futjrnn** [comment]
invite me to discord here with permalink

**Comment by Futjrnn** [comment]
cd $GOPATH/src/github.com/FactomProject/factomd
git checkout master && git pull
glide install
go install

factomd

this worked *tears up*

but still invite me pl0x

**Comment by Emyrk** [comment]
You can find the link at the bottom of this blog post:
https://www.factom.com/blog/factom-community-moving-to-discord-on-march-19

**Comment by Emyrk** [comment]
@Futjrnn So your issue is resolved? Can I close this and your other issue?

**Comment by carryforward** [comment]
try these directions and make sure that golang 1.10 is installed.
https://github.com/FactomProject/FactomDocs/blob/master/installFromSourceDirections.md

**Comment by carryforward** [comment]
don't just do the 'go install' as that doesn't get all the build information into the binary that the build.sh script or the `go install -ldflags "-X github.com/FactomProject/factomd/engine.Build=`git rev-parse HEAD` -X github.com/FactomProject/factomd/engine.FactomdVersion=`cat VERSION`" -v`
