### ISSUE TITLE
API port responds to undocumented http GET verb

### ISSUE THREAD

**Issue by jcheroske** [FactomProject/factomd#622]
While messing around with the API, I discovered that, even though the documentation states that the API is accessed via POST requests, GET requests also work correctly. This seems to be a bug. I don't think the API should respond to GET requests unless it's documented.

**Comment by carryforward** [comment]
what do you think is the best way to fix this?

**Comment by jcheroske** [comment]
Well, you could update the documentation to show that it responds equally to GET and POST, or disable the API from responding to GET requests and return a 405. Those seem to be the two most obvious ways forward. Another approach might be to return a status object instead (see #618), but that could cause some strange behaviour in apps that are currently using the API with GET.

**Comment by stackdump** [comment]
was this related to looking for a way to poll for liveness?

Also - after the change to gorilla mux - we may have slightly different behavior - may take one last comparison before closing - unless there are changes we still need?  @jcheroske
