### ISSUE TITLE
Move from Glide to Go Modules

### ISSUE THREAD

**Issue by AdamSLevy** [FactomProject/factomd#673]
The factomd repository does not include a `go.mod` file which causes or will cause a few issues:
- Golang is officially adopting go modules. As of Golang 1.13 the current build environment using GOPATH will be deprecated.
- Packages that have already adopted Go Modules that also depend on this repository fallback to default dependency resolution behavior which seems to currently fail in various ways.

Challenges/To Do:
- Inter-module dependencies complicate the issue when introducing go.mod to only some repos but not all. 
- Reworking the Dockerfile and CI scripts to be compatible. This is again complicated by the above issue.

Golang [1.11 introduced go modules](https://golang.org/doc/go1.11#modules) as the new dependency management system for Golang. Although it is described as "experimental" in 1.11, as with all go code, "...projects that convert to modules using Go 1.11 will continue to work with Go 1.12 and later."

Golang [1.12 made the `go get` command module aware by default when invoked outside of the GOPATH](https://golang.org/doc/go1.12#modules). 

In the official Golang blog post [Go Modules in 2019](https://blog.golang.org/modules2019) it is stated that Golang 1.13 will "enable module mode by default (that is, to change the default from auto to on) and deprecate GOPATH mode."

It is clear that go modules are here to stay. The advantages are significant. Once fully adopted, all go builds will be completely reproducible, without any external dependency management tool. Fortunately the switch is straightforward and easy, but as with any significant change it will require learning some new things and making some small changes to the CI system. 

A number of questions and concerns with the switch were raised in a Discord conversation. I will try to address them here.

> I am leery of using tags instead of git commit hashes to protect the software.  I don't like the security hole of a dependency moving tags around introducing malicious code in to the build process.

The [`go.sum` file includes cryptographic hashes](https://github.com/golang/go/wiki/Modules#is-gosum-a-lock-file-why-does-gosum-include-information-for-module-versions-i-am-no-longer-using) to properly verify that code has not changed from what was used when the dependency was first checked into the `go.mod` file. If these checksums do not match then the build will fail. This is why it is [important to also check the `go.sum` file into VCS](https://github.com/golang/go/wiki/Modules#should-i-commit-my-gosum-file-as-well-as-my-gomod-file). If a tag is moved (which is of course bad practice) but it is a legitimate change, then the appropriate line in the `go.sum` file can be removed and the new hash will be re-added by running `go mod tidy`.

> This conversation about version ranges brings up alarm bells, since I don't understand the scope of that either, and don't have the bandwidth to understand it.

Go modules use [Semantic Import Versioning](https://github.com/golang/go/wiki/Modules#semantic-import-versioning). This is an application of [semver](https://semver.org/) and a rule that golang has encouraged developers to follow from day one which is now baked into the assumptions that go modules make: "If an old package and a new package have the same import path, the new package must be backwards compatible with the old package." In order to allow for changing APIs in the same repo, go modules interprets an appended  major version to import paths for v2+. For example, if v0 and v1 have the import path "github.com/FactomProject/factomd" then v6 (the current major version) would have the import path "github.com/FactomProject/factomd/v6". Any sub packages in the module follow the major version. For example "github.com/FactomProject/factomd/v6/p2p".

To be continued...

**Comment by stackdump** [comment]
@AdamSLevy  this is slated to (finally) happen during this rewrite effort.

I saw you adopted the `/internal` convention in fatd - that's also something we will work toward.

**Comment by stackdump** [comment]
Spoke about this w/ @WhoSoup  on discord 

we've experimentally tried swapping to go.mod w/ good success
my understanding was that we'd do it for sure in the Wax build

there's just a few other things to alter w/ the Circle.Ci builds to go long w/ this
the Wax build seems to be a good opportunity to re-design the layout

**Comment by stackdump** [comment]
spoke about this in standup w/ @Emyrk 

We'd need to Update Factomd and factom Repos in tandem

**Comment by stackdump** [comment]
Working on this a bit.

We can remove glide for many usages - @Emyrk  raised an issue that we see warnings/errors
when running `go mod tidy` after a naive attempt to convert.

Adding go.mod to a few of the FactomProtocol/<forked-repos> seems to correct this issue.

Though in the case of FactomProtocol/web - we still see an issue when running `go mod tidy` from this project.

Will need to coordinate with @carryforward to figure out a strategy for rolling this out.

**Comment by AdamSLevy** [comment]
Can you post the output of go mod tidy that is causing an issue?

**Comment by stackdump** [comment]
For the FactomProject/web repo:

```
web/examples imports
        github.com/FactomProject/web imports
        container/vector: malformed module path "container/vector": missing dot in first path element
web/examples imports
        github.com/FactomProject/web imports
        http: malformed module path "http": missing dot in first path element
web/examples imports
        github.com/FactomProject/web imports
        utf8: malformed module path "utf8": missing dot in first path element
```
issues seem to be in examples - which I'm sure we can handle

**Comment by stackdump** [comment]
For FactomProject/factom
```
go mod tidy
factom/wallet/wsapi imports
        github.com/FactomProject/factom/wallet: module github.com/FactomProject/factom@latest found (v0.3.5), but does not contain p
ackage github.com/FactomProject/factom/wallet
factom tested by
        factom.test imports
        github.com/FactomProject/factom/wallet/wsapi: module github.com/FactomProject/factom@latest found (v0.3.5), but does not con
tain package github.com/FactomProject/factom/wallet/wsapi
factom/wallet/wsapi imports
        github.com/FactomProject/btcutil/certs tested by
        github.com/FactomProject/btcutil/certs.test imports
        github.com/FactomProject/btcutil imports
        github.com/FactomProject/btcd/btcec: module github.com/FactomProject/btcd@latest found (v0.3.5), but does not contain packag
e github.com/FactomProject/btcd/btcec
```
To try to deal w/ this warning - I added a hack: new empty btcec package
https://github.com/stackdump/btcd/blob/gomod/btcec/btcec.go

In my local testing using the go mod 'replace' directive - this quiets the error while still allowing factomd to build properly.

It also may be that these messages are just an annoyance - but I'd think long term we should be able to get rid of all of them.

**Comment by stackdump** [comment]
I did also try to see what would happen if I swap away from our fork to an upstream repo.
This may be a way forward - but would require significant rewrites.

The direction I got from @carryforward  & @Emyrk was that we'd attempt to keep using these forks.

**Comment by AdamSLevy** [comment]
My recommendation is not to live with or try to hack away these errors, but instead get really familiar with go modules and understand what its telling you.
```
factom/wallet/wsapi imports
        github.com/FactomProject/factom/wallet: module github.com/FactomProject/factom@latest found (v0.3.5), but does not contain package github.com/FactomProject/factom/wallet
```
go mod is trying to figure out what version it should use for "github.com/FactomProject/factom" but it is getting confused by the tagged version numbers. At one point the tag v0.3.5 made its way into the repo but no tag has been published since. Go mod doesn't assume that the tip of master is the latest official version to use if there are tags. When there are tags go mod will use the latest tagged version that matches the major version (there is no major version here). After it resolves the tag v0.3.5, it of course fails to find github.com/FactomProject/factom/wallet, probably because that tag version doesn't have that package or something.

So you need to explicitly tell go mod to use the tip of master (or whatever commit is appropriate). You can do that by running `go get -u github.com/FactomProject/factom@master`. 

Once you tell it what version to use (in the go.mod file "master" will be replaced with a pseudo version string that includes the commit at the tip of master and its timestamp) it should silence that error and build. after this, go mod and go build will not change the version of this dependency again unless you tell it to.

This is also why using the replace directive silences this warning on your local system. The replace directive tells go.mod not to try to use the version listed in the require section, but to just use whatever the replace directive tells it, as if it were the listed version. 

So just go through each of these dependency search issues and explicitly set the version using `go get -u <import-path>@<branch or commit or tag>`.

PM me if you have questions or run into other issues and I'll be happy to help work through them.

**Comment by AdamSLevy** [comment]
Another note: go mod runs recursively so that it can resolve dependencies of dependencies. If you are having errors from a dependency, go fix that dependency's go.mod file first. Get it building with no errors from go.mod. Then go back to the original repo, update the go.mod file so that it points to your latest commits fixing that dependency, and then again attempt `go mod tidy` or `go build`.

**Comment by stackdump** [comment]
Thanks for the Help Adam - this is useful advice.

**Comment by stackdump** [comment]
spoke with @Emyrk  about some choices made here
https://github.com/FactomProject/btcutil/commit/5fd3eaf71bd215f37bfe525ed684f7f29ddaf3d7#commitcomment-37857989

longer term would be nice to ditch these forks in on way or another

**Comment by PaulBernier** [comment]
Latest version of factomd (currently in develop branch, not yet master) uses Go modules and all reference to Glide have been removed.
