### ISSUE TITLE
FD-924 Docker dev environment misconfigured

### ISSUE THREAD

**Issue by WhoSoup** [FactomProject/factomd#677]
This arose from a question in discord/#developer-discussion. The current support/dev docker environment is misconfigured and nodes don't connect to each other. The config files for the three nodes were setup for a network=LOCAL but the command line parameter use network=CUSTOM.

This commit would fix it: https://github.com/FactomProject/factomd/commit/5895c3d51364e7ec20ca74c97c6f63882660361c

**Comment by carryforward** [comment]
ok, this now has a tracking ticket and is scheduled for the parchment release.

**Comment by carryforward** [comment]
what branch is 5895c3d51364e7ec20ca74c97c6f63882660361c in?

can you reformulate it to a pull request to FD-924_reconfigure_dev_docker @WhoSoup ?
