### ISSUE TITLE
FD-922 2nd pass flagging issue on boot

### ISSUE THREAD

**Issue by carryforward** [FactomProject/factomd#683]
Under certain circumstances, these were the symptoms:

The node is booted and it catches up with the federated servers (it is at least very close to being caught up.  it is within a block of the federated servers.)  The issue was also seen on federated servers themselves on reboot, so it is probably not an issue related to trying to catch up.

To observe, look at the control panel after the node has caught up with the first pass.  It has been observed when a node has previously been booted and synced to be current immediately before starting.  The 2nd pass graph will  show that it is caught up with the highest block height.  The 2nd pass will alternate between being behind the 1st pass for 4-8 seconds, then it will show that it advanced to 100% for 10 seconds or so until it reverts back to being behind.

It was not observed closely enough to see when the behavior stops.

This was not verified using the `factom-cli get heights` call.  This would give a different view into the running of the system. It would indicate if it were a control panel issue or if it were deeper in the code.

these were the parameters when starting: `factomd -stderrlog=err.txt -stdoutlog=out.txt -checkheads=false -startdelay=300`

The bug was observed in codebases from 6.2.0 as well as 6.2.2, which are radically different from each other.  

This was the bug as it was seen by Alex from Factoshi.
https://cdn.discordapp.com/attachments/468172332792414209/562947140712923156/sync-bug-6.2.2.gif

It was also seen during the Feb 2019 network pause.  It was likely contributing to federated servers not being able to progress after being restarted.
https://docs.google.com/document/d/1GnhfvlBAg_2gLn6PvFyMmsxVGkl_6cHMJleZnSg_DS0/edit

I have attached the pprof profile from when it was happening. flagging_while_booting.pdf This was the pprof command: `go tool pprof http://localhost:6060/debug/pprof/profile?seconds=30`

I give it a 15% chance that the **leveldb(*tableCompactionBuilder)** was part of what was causing this issue.

The bugfix is currently being attempted by Sander at BIF.

**Comment by carryforward** [comment]
[flagging_while_booting.pdf](https://github.com/FactomProject/factomd/files/3039999/flagging_while_booting.pdf)

**Comment by carryforward** [comment]
Pull requests can go against this branch.  FD-922_2nd_pass_flagging_control_panel

**Comment by afenrir** [comment]
I have created a copy of the blockchain and savestate from a node where this issue reliably occurs. You can download it here: https://factoshi.nyc3.digitaloceanspaces.com/m2.tar.gz
