### ISSUE TITLE
Pending coinbase transactions include non-zero fees 

### ISSUE THREAD

**Issue by afenrir** [FactomProject/factomd#784]
Pending coinbase transactions retrieved using the `pending-transactions` API method have a non-zero fee:

```
 {
    transactionid: '8153434e365d2d7c80b4906a044c86464d2152a23338bcf8bebd77c17ebd4885',
    status: 'TransactionACK',
    inputs: null,
    outputs: null,
    ecoutputs: null,
    fees: 16500
  }
```

The expected behaviour is for the fee to be 0 or null.

**Comment by carryforward** [comment]
This is odd.  Is this causing a problem.  Would @ThomasMeier like to take a look at this?

**Comment by carryforward** [comment]
I'm wondering if the best course of action is to just not return the coinbase as a pending transaction.  I don't know if the timestamp is set when it is a pending transaction, so a transaction ID would be speculative.

**Comment by WhoSoup** [comment]
> I'm wondering if the best course of action is to just not return the coinbase as a pending transaction.

At the moment, the factom-cli doesn't actually show the coinbase when you type `factom-cli get pendingtransactions` (it only shows transactions that have Inputs), but in all other respects, the coinbase transaction is a transaction and should be shown IMO.

Small PR to just not calculate fees for the coinbase transaction: https://github.com/FactomProject/factomd/pull/898

**Comment by stackdump** [comment]
Confirmed this made it to master branch https://github.com/FactomProject/factomd/blob/178ef7174467dd0b4158091a34a7b61cda88a2e2/state/state.go#L1793
