### ISSUE TITLE
ERROR reading config file on Mac

### ISSUE THREAD

**Issue by noguru** [FactomProject/factomd#8]
2016/05/21 11:31:12 read factom config file:  /Users/noguru/.factom/factomd.conf
2016/05/21 11:31:12 ERROR Reading config file!

I always get this error when running factomd. Just got the latest release and it's still there

**Comment by n1rvana** [comment]
Am I correct in assuming you're using the installer?

**Comment by noguru** [comment]
I did use the installer. So any help still appreciated

**Comment by hannemennah** [comment]
Hello,

I just want to mention that this error just means that there was no
factomd.conf file in your home folder. When that is the case, factomd will
automatically use a hard-coded default factomd.conf file, so unless you are
intending to make configuration changes, this error is completely
ignorable, and shouldn't affect performance at all.

Are you seeing any other problems when trying to do things, or is
everything else working as expected?

**Comment by noguru** [comment]
Thanks. I was afraid to try anything because of the error. Maybe it should be a warning? Thanks
