### ISSUE TITLE
[6.5.0] API Diagnostics index out of range error during elections

### ISSUE THREAD

**Issue by WhoSoup** [FactomProject/factomd#947]
I'm moving this error from discord/#testnet-chat over to here so it can get some more visibility. It was originally reported by Allen from HashQuark, which is running `v6.5.0-p2p2-beta1-alpine`, though after my initial investigation, I believe the error is likely part of the core code, not the p2p2 beta code or an incompatibility between the two.

The error is an index out of range error, with the full text here: https://gist.github.com/WhoSoup/9722804f43dbef01ff4f0812cf890d5d

The line that fails is \#1588 in the following block: https://github.com/WhoSoup/factomd/blob/387bb5f63a02f1ff82589a17cb8e98c101742378/wsapi/wsapiV2.go#L1581-L1588

It looks like it could be a multithreading problem caused by an "diagnostics" call during an election where the size of available nodes shrinks by one. `state.GetElections()` isn't thread safe and returns only a reference. It is feasible that between lines \#1582 and \#1588, the state of elections changes so that the index is no longer valid.

**Comment by PaulBernier** [comment]
Just want to report that we lost a Leader on mainnet because of that same error. Hope we can raise the prioritization of that bug. Thanks for the initial investigation Who.

**Comment by stackdump** [comment]
Will be released w/ `A4` build

**Comment by PaulBernier** [comment]
Here's actually the full stacktrace: https://pastebin.com/Nh60C8Ak
it seems the node was caught in an infinite loop of such error? Resulting in an out of memory (line 2237) fatal error, causing the actual crash.

**Comment by stackdump** [comment]
That's interesting - wondering if that's behavior from gorilla to try to re-execute

**Comment by WhoSoup** [comment]
> That's interesting - wondering if that's behavior from gorilla to try to re-execute

According to the timestamps, the remote tool calls the diagnostics endpoint roughly every 5 seconds, seems reasonable. Someone with knowledge of the monitoring code should confirm this.

The odd thing is that the error persisted for at least 38 minutes (until crash). This could be an indicator of a problem inside of the elections code and the api error is only a symptom, not the cause.

**Comment by PaulBernier** [comment]
@WhoSoup @stackdump I see a merged PR and a mention of A4 release, can you confirm this is fixed in current Wax release and we can close? Thanks.

**Comment by WhoSoup** [comment]
> I see a merged PR and a mention of A4 release, can you confirm this is fixed in current Wax release and we can close? Thanks.

It is not fixed in Wax.

**Comment by PaulBernier** [comment]
Oh I see that's one of those fixes that went into master after the Wax branch was created. So hopefully Wax should have it once we reconciliate master and wax rollup. We can keep the issue open until we confirm we were able to merge everything then,

**Comment by PaulBernier** [comment]
@WhoSoup would you mind checking again if this is fixed in 6.9.0-rc2?

**Comment by WhoSoup** [comment]
> @WhoSoup would you mind checking again if this is fixed in 6.9.0-rc2?

Yup, this was one of the merge conflicts and I made sure it got in: 
https://github.com/FactomProject/factomd/blob/4a7c0d121cfbf5950dc217e20c2f5e19e7c8df12/wsapi/wsapiV2.go#L1634-L1643
