### ISSUE TITLE
Add factoids

### ISSUE THREAD

**Issue by vladislavhirko** [FactomProject/factomd#954]
I create the local node, and i try to send tx, but i can't because "Insufficient Fee". How can i generate any factoids for testing?

**Comment by WhoSoup** [comment]
The genesis block for network=LOCAL nodes contains several addresses that come funded with 20,000 FCT each, for example:
```
Fs1jQGc9GJjyWNroLPq7x6LbYQHveyjWNPXSqAvCEKpETNoTU5dP FA22de5NSG2FA2HmMaD4h8qSAZAJyztmmnwgLPghCQKoSekwYYct
Fs3E9gV6DXsYzf7Fqx1fVBQPQXV695eP3k5XbmHEZVRLkMdD9qCK FA2jK2HcLnRdS94dEcU27rF3meoJfpUcZPSinpb7AwQvPRY6RL1Q
Fs2wZzM2iBn4HEbhwEUZjLfcbTo5Rf6ChRNjNJWDiyWmy9zkPQNP FA3heCmxKCk1tCCfiAMDmX8Ctg6XTQjRRaJrF5Jagc9rbo7wqQLV
```

For more info, see here:
https://github.com/FactomProject/factomd/blob/master/common/factoid/genesisBlockNew.go#L35-L40

That should be sufficient to get you started.
